name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

services:
  - xvfb
addons:
  dist: trusty
  chrome: stable
before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=3000 http://localhost &

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    #- run: npm run lint
    - run: npm run test
    - run: xvfb-npm run nightwatch